<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.18.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.14" />
    <PackageReference Include="MimeKit" Version="4.18.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.0-preview.322" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UserService.Application\UserService.Application\UserService.Application.csproj" />
    <ProjectReference Include="..\..\UserService.Domain\UserService.Domain\UserService.Domain.csproj" />
  </ItemGroup>

</Project>
